Bug/support 5708
keboola/component-quickbooks-online pull request #2
Opened 2024-05-02 15:41 UTC by ZdenekSrotyr

2024-05-03 10:19 UTC, SgtMarmite commented
@ZdenekSrotyr Yup, ProfitAndLossQuery is custom made for FHS.

2024-05-03 10:21 UTC, SgtMarmite requested changes

2024-05-03 10:21 UTC, SgtMarmite commented on src/report_mapping.py
> +            logging.warning("Parsing - Key Error or Value Error.")
pls add exception detail

2024-05-06 05:52 UTC, ZdenekSrotyr commented on src/report_mapping.py
> +            logging.warning(f"Parsing error - {type(e).__name__} occurred. Details: {e}")
@SgtMarmite changed

2024-05-06 15:13 UTC, SgtMarmite approved these changes

2024-05-06 15:26 UTC, merged